# Generated by Django 5.0.2 on 2024-03-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dateinvoiced', models.DateField()),
                ('nscheta', models.CharField(max_length=255)),
                ('dogovor', models.CharField(max_length=255)),
                ('datascheta', models.DateField()),
                ('coment', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('bin', models.CharField(max_length=12)),
                ('accountno', models.CharField(max_length=255)),
                ('bank', models.TextField()),
                ('totallines', models.FloatField()),
                ('payamt1c', models.FloatField()),
                ('notpayamt1c', models.FloatField()),
                ('gruppa_proekrov', models.CharField(max_length=255)),
                ('valyuta', models.CharField(max_length=3)),
                ('napravlenie', models.CharField(max_length=255)),
                ('error_txt', models.CharField(max_length=255)),
                ('sumpaid', models.FloatField()),
                ('dname', models.CharField(max_length=255)),
                ('docstatus', models.CharField(max_length=255)),
                ('paydate1c', models.DateField()),
                ('icname', models.CharField(max_length=255)),
                ('chname', models.CharField(max_length=255)),
                ('createdby', models.CharField(max_length=255)),
                ('nomdocument1', models.CharField(blank=True, max_length=255, null=True)),
                ('datadoc', models.DateField(blank=True, null=True)),
                ('komment', models.TextField(blank=True, null=True)),
                ('nepredorigdoc', models.CharField(max_length=255)),
                ('isattached', models.CharField(max_length=1)),
                ('factnumdoc', models.CharField(max_length=255)),
                ('doc_number', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('c_currency_id', models.IntegerField()),
                ('refundamt', models.FloatField()),
                ('daterefund', models.DateField(blank=True, null=True)),
                ('actdocno', models.CharField(max_length=255)),
                ('docserviceact', models.CharField(max_length=255)),
                ('docdate', models.DateField()),
                ('dateprocessed', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('region', models.CharField(max_length=255)),
                ('invoiceamount', models.FloatField()),
                ('security_agreed', models.CharField(max_length=255)),
                ('refundamtkzt', models.FloatField()),
                ('totallineskzt', models.FloatField()),
                ('payamt1ckzt', models.FloatField()),
                ('notpayamt1ckzt', models.FloatField()),
                ('notpayamt1ckztcross', models.FloatField()),
                ('unclosedbalance', models.FloatField()),
                ('c_invoice_id', models.IntegerField()),
                ('postavshik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.counterparty')),
                ('otvzakup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='task.responsible')),
                ('utverditel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='task.responsible')),
            ],
        ),
    ]
