# Generated by Django 5.0.2 on 2024-03-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='datadoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='datascheta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateprocessed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='daterefund',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='paydate1c',
            field=models.CharField(max_length=255),
        ),
    ]
