# Generated by Django 5.0.2 on 2024-03-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_document_datadoc_alter_document_datascheta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='datadoc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='datascheta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateprocessed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='daterefund',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='paydate1c',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='postavshik',
            field=models.CharField(max_length=255),
        ),
    ]
