# Generated by Django 5.0.2 on 2024-03-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_document_datadoc_alter_document_datascheta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='postavshik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.counterparty'),
        ),
    ]
