# Generated by Django 5.0.2 on 2024-03-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_document_postavshik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='c_invoice_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='c_currency_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='datadoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='datascheta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateinvoiced',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateprocessed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='daterefund',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docdate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='invoiceamount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='notpayamt1c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='notpayamt1ckzt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='notpayamt1ckztcross',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='payamt1c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='payamt1ckzt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='paydate1c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='refundamt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='refundamtkzt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='sumpaid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='totallines',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='totallineskzt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='unclosedbalance',
            field=models.CharField(max_length=255),
        ),
    ]
