# Generated by Django 5.0.2 on 2024-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_document_c_invoice_id_alter_document_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='c_invoice_id',
            field=models.IntegerField(null=True),
        ),
    ]
