# Generated by Django 5.0.2 on 2024-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_document_c_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='paydate1c',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
