# Generated by Django 5.0.2 on 2024-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_document_paydate1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='refundamt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
