# Generated by Django 5.0.2 on 2024-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_document_refundamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='refundamtkzt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
