# Generated by Django 5.0.2 on 2024-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_document_refundamtkzt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='payamt1ckzt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
