# Generated by Django 5.0.2 on 2024-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_document_accountno_alter_document_actdocno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='accountno',
            field=models.TextField(null=True),
        ),
    ]
