# Generated by Django 5.0.2 on 2024-03-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_document_actdocno_alter_document_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='coment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='datascheta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateinvoiced',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='dogovor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='nscheta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
