# Generated by Django 5.0.2 on 2024-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_document_utverditel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='bin',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
