# Generated by Django 5.0.2 on 2024-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_counterparty_bin_alter_counterparty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='utverditel',
            field=models.TextField(null=True),
        ),
    ]
